name: Coverage

on: ["push", "pull_request"]

jobs:
  build:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.dev.txt
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install -e .
          fi
          pip install coveralls

      - name: Run Coverage
        run: coverage run --source rawl -m py.test

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
